site_name: Cookiecutter Dash docset
repo_url: https://github.com/paw-lu/cookiecutter-dash-docset/
site_url: https://paw-lu.github.io/cookiecutter-dash-docset/

nav:
  - index.md
  - generating_a_project.md
  - modifying_the_project.md
  - running_the_project_locally.md
  - code_quality_tools.md
  - advanced_github_actions_features.md
  - how_it_works.md

plugins:
  - search
  - social

theme:
  name: material

  features:
    - navigation.instant
    - content.code.annotate

  icon:
    repo: material/github
    logo: material/cookie

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: teal
      toggle:
        name: Switch to dark mode
        icon: material/brightness-2

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: cyan
      toggle:
        name: Switch to light mode
        icon: material/brightness-5

markdown_extensions:
  - attr_list
  - pymdownx.superfences
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - footnotes
  - tables

  - pymdownx.tasklist:
      custom_checkbox: true

  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.highlight:
      use_pygments: true
