name: ci
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Setup Nox
        id: setup-nox
        uses: wntrblm/nox@2022.8.7
        with:
          python-versions: "3.10"

      - name: Deploy docs
        id: deploy-docs
        run: |
          nox --sessions deploy-docs
