name: Docs
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      FORCE_COLOR: "1"

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Setup Nox
        id: setup-nox
        uses: wntrblm/nox@2022.8.7
        with:
          python-versions: "3.10"

      - name: Build docs
        id: build-docs
        if: ${{ github.ref_name != 'main' }}
        run: |
          nox --sessions docs

      - name: Deploy docs
        id: deploy-docs
        if: ${{ github.ref_name == 'main' && github.event_name == 'push' }}
        run: |
          nox --sessions deploy-docs
