name: Generate
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: generate
    runs-on: ubuntu-latest

    env:
      FORCE_COLOR: "1"

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          path: cookiecutter-dash-docset

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Set up cookiecutter
        working-directory: cookiecutter-dash-docset
        run: |
          pipx install --pip-args=--constraint=.github/workflows/constraints.txt cookiecutter
          cookiecutter --version

      - name: Setup Nox
        uses: wntrblm/nox@2022.11.21
        with:
          python-versions: "3.10"

      - name: Set up pre-commit
        working-directory: cookiecutter-dash-docset
        run: |
          pipx install --pip-args=--constraint=.github/workflows/constraints.txt pre-commit
          pre-commit --version

      - name: Generate project
        run: |
          cookiecutter --no-input cookiecutter-dash-docset

      - name: Create git repository
        working-directory: pip-dash-docset
        run: |
          git init
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add --all
          git commit --message="Init"

      - name: Run pre-commit
        working-directory: pip-dash-docset
        run: |
          pre-commit run --show-diff-on-failure --all-files

      - name: Run nox
        working-directory: pip-dash-docset
        run: |
          nox --session=check-types -- --strict --config-file=
